permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Teased"
  description: |
    Teased is an independent specialty tea shop that keeps young tea lovers excited on health benefits.
  font_url: "https://use.typekit.net/nyj5mkf.css"
  colors:
    background: "--color-primary"
    accent: "--color-primary-pair"
    patterns:
      brand.logos: "--color-primary"
  rationales:
    typefaces.primary: |
      Futura was selected because of it's trendy strong Geometric Sans feel. Futura is to be used for all body copy and all situations.
    colors.primary: |
      The primary color will only be used for background colors. Never use as text color.

      - On "Teas" page - use primary color for the background of: Black Teas.
      - On "Product Description" page - use primary color as the background color for the grid below the product description.
      - On "Cart" page - use primary color for the Shipping address background header color.

      The primary pair color will be used only as an accent color to our primary color. Never use as text color.

      - On "Teas" page - use primary pair color for the line in the header of: Black Teas
      - On "Cart" page - use primary pair color for the line in the header of: Shipping Address.

      The primary pair opacity color will only ever be used on our image hovers.

      - On "Teas" page - use this opacity color for product image hovers for the Black Tea section.
    colors.secondary: |
