description: |
  The buttons are to be used to showcase the websites most important features.

  Buttons can be combined with banners, images, and the header.
patterns:
  basic:
    title: "Basic"
    description: |
      Basic buttons are used for the quantity grid section on Product Description page. Or the checkout place order.
  button-place:
    title: "Button Place"
    description: |
      Button Place buttons are used for the quantity grid section on Product Description page. Or the checkout place order.
    Ghost:
      title: "Ghost"
      description: |
        Ghost buttons are used for call to action banners section on our homepage. Can be used on any call to action banner throughout the website.
