description: |
  The cards are to be used to showcase the websites most important features.

  Cards can be combined with images and throughout section grids.
patterns:
  tea-card:
    title: "Black Tea Card"
    description: |
      Black Tea Cards are used only specifically for Black teas. Can be used in a grid grouping or individually.
    fields:
      - name: teaimage
        type: string
        example: "white-punch.jpg"
  checkout-card:
    title: "Checkout Card"
    description: |
      Checkout Cards are used only specifically for product checkout cart. Can be used in a grid grouping or individually.
    fields:
      - name: totaled
        type: string
        example: "9.99"
      - name: amountoftea
        type: string
        example: "3"
      - name: teaimage
        type: string
        example: "white-punch.jpg"
      - name: productname
        type: string
        example: "Black Tea"
